baseURL: "https://jwlee9.github.io/home/"
title: Jaewon Lee
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: projects/
          weight: 1
        - name: Music
          url: music/
          weight: 2

params:
    description: "This is Jaewon Lee's website."
    author: Jaewon Lee
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","music"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jaewon Lee
          subtitle: "<span class='subtitle'>I am a composer, pianist, and undergraduate researcher at <a href='https://www.hearo-kist.com/' style='text-decoration: underline;'>the HEA-RO Lab</a> at the Korea Institute of Science and Technology (KIST). My work brings together music, auditory neuroscience, and computer science.</span>"
          imageUrl: "jaewon-profile.jpg"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: CV
              url: cv.pdf
            - name: Research
              url: projects/
            - name: Music
              url: music/

    socialIcons:
        - name: Email
          url: mailto:jwlee9@snu.ac.kr
        - name: YouTube
          url: https://www.youtube.com/@jwlee3
        - name: GitHub
          url: https://github.com/jwlee9

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jaewon Lee"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
