baseURL: "https://jwlee9.github.io/home/"
title: Jaewon Lee
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: projects/
          weight: 1
        - name: Schedule
          url: schedule/
          weight: 2

params:
    description: "This is Jaewon Lee's website."
    author: Jaewon Lee
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jaewon Lee
          subtitle: "<span class='subtitle'>Hi there! I am an undergraduate student at <a href='https://snu.ac.kr' style='text-decoration: underline;'>Seoul National University</a>, majoring in Music Composition and Computer Science and Engineering. My passion lies in the intersection of music, neuroscience, and computer-based technology. Alongside my studies, I work as an Undergraduate Researcher at the <a href='https://www.hearo-kist.com/' style='text-decoration: underline;'>HEA-RO Lab</a>, where I assist EEG research in Auditory Neuroscience. </span>"
          imageUrl: "jaewon-profile.jpg"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: CV
              url: cv.pdf
            - name: Research
              url: projects/

    socialIcons:
        - name: Email
          url: mailto:jwlee9@snu.ac.kr
        - name: YouTube
          url: https://www.youtube.com/@jwlee3
        - name: GitHub
          url: https://github.com/jwlee9

    assets:
        disableScrollBarStyle: true
        favicon: banana.svg
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jaewon Lee"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
